#!/bin/bash

# This script monitors if my dad's computer is online
# if it is, then stop torrent downloads (as he's always complaining about slow rates)
# if he's off, go nuts with downloading

killall deluge-console 2>/dev/null
killall deluge-monitor 2>/dev/null

HOST="192.168.178.20"
ping -c1 ${HOST} -q 2>&1 >/dev/null
RET=$?
if [ ${RET} -eq 0 ]; then
	#we were successful. disable downloads
	/usr/bin/deluge-console "config --set max_active_limit 0" 2>&1 >/dev/null
else
	#we weren’t successful. download away
	/usr/bin/deluge-console "config --set max_active_limit 100" 2>&1 >/dev/null
fi
