#!/bin/bash
length=$(($#-1))
allbutlast=${@:1:$length}
last=${@:$length+1:$length + 2}

if [[ "$last" = "!" ]] ; then
	mpc clear >/dev/null
        mpc random off >/dev/null
        mpc search album "$allbutlast" | mpc add >/dev/null
        mpc search album "$allbutlast" | awk -F/ '{print $1 " - "$2}' | uniq | sort
        echo ""
        mpc play 1
else
	mpc search any "$*" | awk -F/ '{print $1 " - "$2}' | uniq | sort
fi
