#!/bin/bash
length=$(($#-1))
allbutlast=${@:1:$length}
last=${@:$length+1:$length + 2}

if [[ "$last" = "!" ]] ; then
	mpc clear >/dev/null
        mpc random off >/dev/null
        mpc search album "$allbutlast" | mpc add
        echo ""
        mpc play 1
else
	mpc search any "$*"
fi
