#!/bin/bash
length=$(($#-1))
allbutlast=${@:1:$length}
last=${@:$length+1:$length + 2}

if [[ "$last" = "!" ]] ; then
        mpc clear >/dev/null
        mpc random on >/dev/null
        mpc search artist "$allbutlast" | mpc add
        echo ""
        mpc play
else
        mpc search artist "$*"
fi
